# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Learning, unsupervised
email:
description: >- # this means to ignore newlines until "baseurl:"
  Learning to train and training to learn how to analyze data & code in Python and R.

url : "https://limegimlet.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
#baseurl : "/learning" # the subpath of your site, e.g. "/blog"

twitter_username: sehosking
github_username: limegimlet
minimal_mistakes_skin: default
search: true
github: [metadata]

# tracking info
analytics:
  provider : "google"
  google:
    tracking_id : "G-WJK93JJHWP"

# Build settings
markdown: kramdown
remote_theme: limegimlet/minimal-mistakes
#remote_theme: joshgerdes/jekyll-uno

# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Europe/Paris # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-remote-theme

author:
  name   : "S. Hosking"
  #avatar : "/assets/images/bio-photo.jpg"
  #bio    : "My awesome biography constrained to a sentence or two goes here."
  bio     : "Explainer. Cyclist. Data analyst. Aspiring Data Scientist."
  location : "Paris, France"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://limegimlet.github.io/covid_dataviz"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sehosking"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/sehosking/"
    #- label: "GitHub"
    #  icon: "fab fa-fw fa-github"
    #  url: "https://github.com/limegimlet"
    #- label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
    #  url: "https://instagram.com/"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/sehosking"
    #- label: "GitHub"
     # icon: "fab fa-fw fa-github"
      #url: "https://github.com/limegimlet"
    #- label: "Instagram"
    #  icon: "fab fa-fw fa-instagram"
    #  url: "https://instagram.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: splash
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
